// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// colsbm_create
XPtr<ColSBM> colsbm_create(List A, int Q, List tau, bool directed, std::string distribution, bool free_mixture, bool free_density);
RcppExport SEXP _colSBM_colsbm_create(SEXP ASEXP, SEXP QSEXP, SEXP tauSEXP, SEXP directedSEXP, SEXP distributionSEXP, SEXP free_mixtureSEXP, SEXP free_densitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type Q(QSEXP);
    Rcpp::traits::input_parameter< List >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< std::string >::type distribution(distributionSEXP);
    Rcpp::traits::input_parameter< bool >::type free_mixture(free_mixtureSEXP);
    Rcpp::traits::input_parameter< bool >::type free_density(free_densitySEXP);
    rcpp_result_gen = Rcpp::wrap(colsbm_create(A, Q, tau, directed, distribution, free_mixture, free_density));
    return rcpp_result_gen;
END_RCPP
}
// colsbm_optimize
void colsbm_optimize(XPtr<ColSBM> ptr, int max_step, double tol);
RcppExport SEXP _colSBM_colsbm_optimize(SEXP ptrSEXP, SEXP max_stepSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ColSBM> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type max_step(max_stepSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    colsbm_optimize(ptr, max_step, tol);
    return R_NilValue;
END_RCPP
}
// colsbm_vbound
double colsbm_vbound(XPtr<ColSBM> ptr);
RcppExport SEXP _colSBM_colsbm_vbound(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ColSBM> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(colsbm_vbound(ptr));
    return rcpp_result_gen;
END_RCPP
}
// colsbm_info
List colsbm_info(XPtr<ColSBM> ptr);
RcppExport SEXP _colSBM_colsbm_info(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<ColSBM> >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(colsbm_info(ptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_colSBM_colsbm_create", (DL_FUNC) &_colSBM_colsbm_create, 7},
    {"_colSBM_colsbm_optimize", (DL_FUNC) &_colSBM_colsbm_optimize, 3},
    {"_colSBM_colsbm_vbound", (DL_FUNC) &_colSBM_colsbm_vbound, 1},
    {"_colSBM_colsbm_info", (DL_FUNC) &_colSBM_colsbm_info, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_colSBM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
