# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colsbm_create <- function(A, Q, tau, directed = FALSE, distribution = "bernoulli", free_mixture = TRUE, free_density = TRUE) {
    .Call('_colSBM_colsbm_create', PACKAGE = 'colSBM', A, Q, tau, directed, distribution, free_mixture, free_density)
}

colsbm_optimize <- function(ptr, max_step = 100L, tol = 1e-6) {
    invisible(.Call('_colSBM_colsbm_optimize', PACKAGE = 'colSBM', ptr, max_step, tol))
}

colsbm_vbound <- function(ptr) {
    .Call('_colSBM_colsbm_vbound', PACKAGE = 'colSBM', ptr)
}

colsbm_info <- function(ptr) {
    .Call('_colSBM_colsbm_info', PACKAGE = 'colSBM', ptr)
}

#' Reimplementation of quadratic form in C++
#'
#' @param x the quadratic form
#' @param y the matrix on which x is applied
#'
#' @return t(x)%*% y %*% x, but faster I hope
tquadform_cpp <- function(x, y) {
    .Call('_colSBM_tquadform_cpp', PACKAGE = 'colSBM', x, y)
}

