# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colsbm_create <- function(A, Q) {
    .Call(`_colSBM_colsbm_create`, A, Q)
}

colsbm_optimize <- function(ptr, max_step = 100L, tol = 1e-6) {
    invisible(.Call(`_colSBM_colsbm_optimize`, ptr, max_step, tol))
}

colsbm_vbound <- function(ptr) {
    .Call(`_colSBM_colsbm_vbound`, ptr)
}

colsbm_info <- function(ptr) {
    .Call(`_colSBM_colsbm_info`, ptr)
}

